# Generated by Django 6.0.5 on 2026-05-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiprocketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('awb_code', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shiprocket Log',
                'verbose_name_plural': 'Shiprocket Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiprocketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('pickup_location', models.CharField(default='Primary', max_length=100)),
                ('company_name', models.CharField(default='Sanjari Prints', max_length=200)),
                ('phone', models.CharField(default='+91', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('default_weight', models.FloatField(default=0.5)),
                ('default_length', models.IntegerField(default=25)),
                ('default_breadth', models.IntegerField(default=20)),
                ('default_height', models.IntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shiprocket Settings',
                'verbose_name_plural': 'Shiprocket Settings',
            },
        ),
        migrations.CreateModel(
            name='ShiprocketToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Shiprocket Token',
                'verbose_name_plural': 'Shiprocket Tokens',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ShiprocketShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, max_length=100)),
                ('awb_code', models.CharField(blank=True, max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('label_url', models.URLField(blank=True)),
                ('manifest_url', models.URLField(blank=True)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(default='created', max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='payments.order')),
            ],
        ),
    ]
