# Generated by Django 6.0.5 on 2026-07-08 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_fileitem_remote_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_id', models.UUIDField()),
                ('admin_email', models.TextField()),
                ('admin_name', models.TextField()),
                ('action', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Website Admin Audit Log',
                'verbose_name_plural': 'Website Admin Audit Logs',
                'db_table': 'admin_audit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Content Page',
                'verbose_name_plural': 'Website Content Pages',
                'db_table': 'content_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website FAQ',
                'verbose_name_plural': 'Website FAQs',
                'db_table': 'faqs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewaySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_enabled', models.BooleanField(default=False)),
                ('razorpay_key_id', models.TextField(blank=True, null=True)),
                ('razorpay_key_secret', models.TextField(blank=True, null=True)),
                ('phonepe_enabled', models.BooleanField(default=True)),
                ('phonepe_merchant_id', models.TextField(blank=True, null=True)),
                ('phonepe_salt_key', models.TextField(blank=True, null=True)),
                ('phonepe_salt_index', models.TextField(blank=True, null=True)),
                ('cod_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Payment Gateway Setting',
                'verbose_name_plural': 'Website Payment Gateway Settings',
                'db_table': 'payment_gateway_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('subcategory', models.TextField()),
                ('rules', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Pricing Rule',
                'verbose_name_plural': 'Website Pricing Rules',
                'db_table': 'pricing_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('subcategory', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Product',
                'verbose_name_plural': 'Website Products',
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('order_number', models.TextField(unique=True)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.TextField(default='pending')),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('payment_status', models.TextField(default='pending')),
                ('tracking_number', models.TextField(blank=True, null=True)),
                ('tracking_url', models.TextField(blank=True, null=True)),
                ('estimated_delivery', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Order',
                'verbose_name_plural': 'Website Orders',
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('user_name', models.TextField()),
                ('user_email', models.TextField()),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website Review',
                'verbose_name_plural': 'Website Reviews',
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_path', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('og_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website SEO Setting',
                'verbose_name_plural': 'Website SEO Settings',
                'db_table': 'seo_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupabaseUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('role', models.TextField(default='user')),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Website User',
                'verbose_name_plural': 'Website Users',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Backend Checkout Order', 'verbose_name_plural': 'Backend Checkout Orders'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Packaging / Shipping Setting', 'verbose_name_plural': 'Packaging & Shipping Charges'},
        ),
    ]
